# GitLab CI/CD Example for LiteLLM Gateway
# Purpose: Automate gateway deployment and testing in GitLab CI
# Usage: Copy to .gitlab-ci.yml or include in your existing pipeline

stages:
  - validate
  - test
  - deploy

variables:
  LITELLM_PORT: "4000"
  PYTHON_VERSION: "3.9"

# Validate configuration files
validate-config:
  stage: validate
  image: python:${PYTHON_VERSION}
  before_script:
    - pip install --upgrade pip
    - pip install litellm pyyaml
  script:
    - echo "Validating LiteLLM configuration..."
    - python3 specs/001-llm-gateway-config/scripts/validate-config.py config/litellm.yaml
    - python3 -c "import yaml; yaml.safe_load(open('config/litellm.yaml'))" && echo "✅ YAML syntax valid"
  only:
    changes:
      - config/litellm*.yaml
      - .gitlab-ci.yml

# Test gateway health
test-gateway:
  stage: test
  image: python:${PYTHON_VERSION}
  before_script:
    - pip install --upgrade pip
    - pip install litellm google-cloud-aiplatform
    - |
      # Authenticate to Google Cloud
      echo "$GCP_SA_KEY" | base64 -d > /tmp/gcp-key.json
      export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json
  script:
    - echo "Starting LiteLLM gateway..."
    - litellm --config config/litellm.yaml --port ${LITELLM_PORT} &
    - sleep 15
    - |
      # Health check
      curl -f http://localhost:${LITELLM_PORT}/health || exit 1
      echo "✅ Gateway health check passed"
    - |
      # Test model availability
      python3 specs/001-llm-gateway-config/scripts/check-model-availability.py \
        --config config/litellm.yaml \
        --models gemini-2.5-flash,gemini-2.5-pro
  only:
    changes:
      - config/litellm*.yaml
      - .gitlab-ci.yml
  variables:
    GCP_SA_KEY: $GCP_SA_KEY  # Set in GitLab CI/CD variables

# Deploy to staging
deploy-staging:
  stage: deploy
  image: alpine:latest
  script:
    - echo "🚀 Deploying to staging environment"
    - |
      # Add your deployment commands here
      # Example: kubectl apply, terraform apply, etc.
      echo "Deployment commands would go here"
  environment:
    name: staging
    url: https://gateway-staging.example.com
  only:
    - develop
  when: manual

# Deploy to production
deploy-production:
  stage: deploy
  image: alpine:latest
  script:
    - echo "🚀 Deploying to production environment"
    - |
      # Add your deployment commands here
      echo "Production deployment commands would go here"
  environment:
    name: production
    url: https://gateway.example.com
  only:
    - main
  when: manual

